<?php
# MetInfo Enterprise Content Management System 
# Copyright (C) MetInfo Co.,Ltd (http://www.metinfo.cn). All rights reserved.

defined('IN_MET') or exit('No permission');

define ('TEM_INSTALL_VER', '1.000');

class install {
	function dosql(){
		global $_M;		
		
$sql = array (
  0 => 'pos =\'2\',no_order=\'1\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_download\',value=\'\',defaultvalue=\'\',valueinfo =\'下载模块\',tips=\'\',bigclass =\'0\'',
  1 => 'pos =\'3\',no_order=\'1\',type=\'1\',style=\'3\',selectd=\'\',name =\'news_bar\',value=\'\',defaultvalue=\'\',valueinfo =\'文章模块\',tips=\'\',bigclass =\'0\'',
  2 => 'pos =\'1\',no_order=\'1\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_index_product\',value=\'\',defaultvalue=\'\',valueinfo =\'首页产品区块\',tips=\'\',bigclass =\'0\'',
  3 => 'pos =\'0\',no_order=\'1\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_head\',value=\'\',defaultvalue=\'\',valueinfo =\'顶部设置\',tips=\'\',bigclass =\'0\'',
  4 => 'pos =\'2\',no_order=\'2\',type=\'2\',style=\'3\',selectd=\'\',name =\'download\',value=\'立即下载\',defaultvalue=\'立即下载\',valueinfo =\'按钮文字\',tips=\'\',bigclass =\'259\'',
  5 => 'pos =\'3\',no_order=\'2\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'bar_column3_open\',value=\'1\',defaultvalue=\'1\',valueinfo =\'三级栏目开关\',tips=\'除开产品模块以外的侧栏\',bigclass =\'261\'',
  6 => 'pos =\'1\',no_order=\'2\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_product_title\',value=\'标题\',defaultvalue=\'标题\',valueinfo =\'区块标题\',tips=\'\',bigclass =\'285\'',
  7 => 'pos =\'0\',no_order=\'2\',type=\'2\',style=\'3\',selectd=\'\',name =\'nav_ml\',value=\'10\',defaultvalue=\'10\',valueinfo =\'导航间距\',tips=\'默认是0，仅支持5的倍数（0/5/10/15/20...最大50）<br/>不同网站的导航数量不同，根据需求适当调整间距，让网站更协调。\',bigclass =\'309\'',
  8 => 'pos =\'3\',no_order=\'3\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'bar_column_open\',value=\'1\',defaultvalue=\'1\',valueinfo =\'侧栏栏目开关\',tips=\'除开产品模块以外的侧栏\',bigclass =\'261\'',
  9 => 'pos =\'1\',no_order=\'3\',type=\'3\',style=\'3\',selectd=\'\',name =\'index_product_desc\',value=\'描述\',defaultvalue=\'描述\',valueinfo =\'区块描述\',tips=\'\',bigclass =\'285\'',
  10 => 'pos =\'0\',no_order=\'3\',type=\'2\',style=\'3\',selectd=\'\',name =\'all\',value=\'全部\',defaultvalue=\'全部\',valueinfo =\'下拉菜单全部\',tips=\'仅在手机端显示\',bigclass =\'309\'',
  11 => 'pos =\'2\',no_order=\'3\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_img\',value=\'\',defaultvalue=\'\',valueinfo =\'图片模块\',tips=\'\',bigclass =\'0\'',
  12 => 'pos =\'3\',no_order=\'4\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'news_bar_list_open\',value=\'1\',defaultvalue=\'1\',valueinfo =\'侧栏文章列表开关\',tips=\'\',bigclass =\'261\'',
  13 => 'pos =\'1\',no_order=\'4\',type=\'6\',style=\'3\',selectd=\'\',name =\'index_product_id\',value=\'\',defaultvalue=\'\',valueinfo =\'调用栏目\',tips=\'\',bigclass =\'285\'',
  14 => 'pos =\'2\',no_order=\'4\',type=\'4\',style=\'3\',selectd=\'$M$浏览模式$T$1$M$详情模式$T$0\',name =\'img_listlook_style\',value=\'1\',defaultvalue=\'1\',valueinfo =\'查看模式\',tips=\'浏览模式为在列表页浏览图片，详情模式为点击进入详情页\',bigclass =\'350\'',
  15 => 'pos =\'0\',no_order=\'4\',type=\'4\',style=\'3\',selectd=\'开启$T$1$M$关闭$T$0\',name =\'lang_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'多语言\',tips=\'在系统开启语言切换的前提下进行设置\',bigclass =\'309\'',
  16 => 'pos =\'3\',no_order=\'5\',type=\'2\',style=\'3\',selectd=\'\',name =\'news_bar_list_title\',value=\'为您推荐\',defaultvalue=\'为您推荐\',valueinfo =\'侧栏文章列表标题\',tips=\'\',bigclass =\'261\'',
  17 => 'pos =\'1\',no_order=\'5\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_product_all\',value=\'全部\',defaultvalue=\'全部\',valueinfo =\'栏目列表代表文字\',tips=\'\',bigclass =\'285\'',
  18 => 'pos =\'2\',no_order=\'5\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_job\',value=\'\',defaultvalue=\'\',valueinfo =\'招聘模块\',tips=\'\',bigclass =\'0\'',
  19 => 'pos =\'0\',no_order=\'5\',type=\'4\',style=\'3\',selectd=\'头部$T$1$M$底部$T$0\',name =\'lang_position\',value=\'1\',defaultvalue=\'1\',valueinfo =\'多语言位置\',tips=\'\',bigclass =\'309\'',
  20 => 'pos =\'1\',no_order=\'6\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_product_column_xxl\',value=\'4\',defaultvalue=\'4\',valueinfo =\'大尺寸电脑显示列数\',tips=\'浏览器宽度大于1600像素时\',bigclass =\'285\'',
  21 => 'pos =\'2\',no_order=\'6\',type=\'2\',style=\'3\',selectd=\'\',name =\'cvtitle\',value=\'在线应聘\',defaultvalue=\'在线应聘\',valueinfo =\'按钮文字\',tips=\'\',bigclass =\'299\'',
  22 => 'pos =\'0\',no_order=\'6\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'langlist_icon_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'语言国旗开关\',tips=\'\',bigclass =\'309\'',
  23 => 'pos =\'3\',no_order=\'6\',type=\'4\',style=\'3\',selectd=\'全部$T$all$M$推荐$T$com\',name =\'news_bar_list_type1\',value=\'all\',defaultvalue=\'all\',valueinfo =\'侧栏列表文章类型\',tips=\'\',bigclass =\'261\'',
  24 => 'pos =\'3\',no_order=\'7\',type=\'2\',style=\'3\',selectd=\'\',name =\'news_bar_list_num\',value=\'5\',defaultvalue=\'5\',valueinfo =\'侧栏列表文章数量\',tips=\'\',bigclass =\'261\'',
  25 => 'pos =\'1\',no_order=\'7\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_product_column_lg\',value=\'4\',defaultvalue=\'4\',valueinfo =\'普通电脑显示列数\',tips=\'浏览器宽度大于992像素小于1600像素时\',bigclass =\'285\'',
  26 => 'pos =\'2\',no_order=\'7\',type=\'1\',style=\'3\',selectd=\'\',name =\'subcolumn_nav\',value=\'\',defaultvalue=\'\',valueinfo =\'子栏目设置\',tips=\'\',bigclass =\'0\'',
  27 => 'pos =\'0\',no_order=\'7\',type=\'4\',style=\'3\',selectd=\'开启$T$1$M$关闭$T$0\',name =\'simplified\',value=\'1\',defaultvalue=\'1\',valueinfo =\'简繁体切换\',tips=\'在系统开启简繁体切换的前提下进行设置\',bigclass =\'309\'',
  28 => 'pos =\'1\',no_order=\'8\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_product_column_md\',value=\'2\',defaultvalue=\'2\',valueinfo =\'平板显示列数\',tips=\'浏览器宽度大于768像素小于992像素时\',bigclass =\'285\'',
  29 => 'pos =\'2\',no_order=\'8\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'tagshow_2\',value=\'1\',defaultvalue=\'1\',valueinfo =\'区块开关\',tips=\'\',bigclass =\'348\'',
  30 => 'pos =\'3\',no_order=\'8\',type=\'4\',style=\'3\',selectd=\'开启$T$1$M$关闭$T$0\',name =\'news_bar_list_rot\',value=\'1\',defaultvalue=\'1\',valueinfo =\'热门产品开关\',tips=\'\',bigclass =\'261\'',
  31 => 'pos =\'0\',no_order=\'8\',type=\'4\',style=\'3\',selectd=\'头部$T$1$M$底部$T$0\',name =\'cn1_position\',value=\'1\',defaultvalue=\'1\',valueinfo =\'简繁体位置\',tips=\'\',bigclass =\'309\'',
  32 => 'pos =\'1\',no_order=\'9\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_product_column_xs\',value=\'2\',defaultvalue=\'2\',valueinfo =\'手机显示列数\',tips=\'浏览器宽度小于768像素时\',bigclass =\'285\'',
  33 => 'pos =\'2\',no_order=\'9\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_news\',value=\'\',defaultvalue=\'\',valueinfo =\'文章模块\',tips=\'\',bigclass =\'0\'',
  34 => 'pos =\'3\',no_order=\'9\',type=\'6\',style=\'3\',selectd=\'\',name =\'id\',value=\'\',defaultvalue=\'\',valueinfo =\'热门产品栏目\',tips=\'\',bigclass =\'261\'',
  35 => 'pos =\'0\',no_order=\'9\',type=\'4\',style=\'3\',selectd=\'固定$T$1$M$不固定$T$0\',name =\'navfixed_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'导航固定\',tips=\'固定状态下页面往下滚动时，导航也会跟随。\',bigclass =\'309\'',
  36 => 'pos =\'1\',no_order=\'10\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_product_allnum\',value=\'8\',defaultvalue=\'8\',valueinfo =\'调用条数\',tips=\'每个列表调用信息最多条数\',bigclass =\'285\'',
  37 => 'pos =\'2\',no_order=\'10\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'news_imgok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'图片开关\',tips=\'\',bigclass =\'359\'',
  38 => 'pos =\'3\',no_order=\'10\',type=\'2\',style=\'3\',selectd=\'\',name =\'news_bar_list_rot_num\',value=\'3\',defaultvalue=\'3\',valueinfo =\'热门产品调用条数\',tips=\'\',bigclass =\'261\'',
  39 => 'pos =\'0\',no_order=\'10\',type=\'4\',style=\'3\',selectd=\'开启$T$1$M$关闭$T$0\',name =\'member\',value=\'1\',defaultvalue=\'1\',valueinfo =\'会员注册开关\',tips=\'\',bigclass =\'309\'',
  40 => 'pos =\'2\',no_order=\'11\',type=\'4\',style=\'3\',selectd=\'$M$全部$T$all$M$推荐$T$com\',name =\'news_bar_list_type\',value=\'all\',defaultvalue=\'all\',valueinfo =\'侧栏列表文章类型\',tips=\'\',bigclass =\'359\'',
  41 => 'pos =\'1\',no_order=\'11\',type=\'4\',style=\'3\',selectd=\'全部$T$all$M$推荐$T$com\',name =\'index_product_type\',value=\'all\',defaultvalue=\'all\',valueinfo =\'调用类型\',tips=\'列表信息调用类型，【推荐】可以在添加或管理文章列表时设置。\',bigclass =\'285\'',
  42 => 'pos =\'3\',no_order=\'11\',type=\'2\',style=\'3\',selectd=\'\',name =\'news_bar_list_rot_title\',value=\'热门产品\',defaultvalue=\'热门产品\',valueinfo =\'热门产品标题\',tips=\'\',bigclass =\'261\'',
  43 => 'pos =\'0\',no_order=\'11\',type=\'2\',style=\'3\',selectd=\'\',name =\'adress\',value=\'\',defaultvalue=\'\',valueinfo =\'地址\',tips=\'\',bigclass =\'309\'',
  44 => 'pos =\'1\',no_order=\'12\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_product_img_w\',value=\'484\',defaultvalue=\'484\',valueinfo =\'缩略图宽\',tips=\'默认为484px\',bigclass =\'285\'',
  45 => 'pos =\'3\',no_order=\'12\',type=\'1\',style=\'3\',selectd=\'\',name =\'downlaod_bar\',value=\'\',defaultvalue=\'\',valueinfo =\'下载模块\',tips=\'\',bigclass =\'0\'',
  46 => 'pos =\'0\',no_order=\'12\',type=\'3\',style=\'3\',selectd=\'\',name =\'adress1\',value=\'\',defaultvalue=\'\',valueinfo =\'详细地址\',tips=\'关闭会员功能默认显示，开启会员功能则默认关闭\',bigclass =\'309\'',
  47 => 'pos =\'2\',no_order=\'12\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_sidebar\',value=\'\',defaultvalue=\'\',valueinfo =\'产品列表侧边栏\',tips=\'\',bigclass =\'0\'',
  48 => 'pos =\'1\',no_order=\'13\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_product_img_h\',value=\'300\',defaultvalue=\'300\',valueinfo =\'缩略图高\',tips=\'默认为300px\',bigclass =\'285\'',
  49 => 'pos =\'3\',no_order=\'13\',type=\'2\',style=\'3\',selectd=\'\',name =\'download_bar_list_title\',value=\'为你推荐\',defaultvalue=\'为你推荐\',valueinfo =\'侧栏下载列表标题\',tips=\'\',bigclass =\'352\'',
  50 => 'pos =\'0\',no_order=\'13\',type=\'2\',style=\'3\',selectd=\'\',name =\'tel\',value=\'\',defaultvalue=\'\',valueinfo =\'电话\',tips=\'关闭会员功能默认显示，开启会员功能则默认关闭\',bigclass =\'309\'',
  51 => 'pos =\'2\',no_order=\'13\',type=\'4\',style=\'3\',selectd=\'开启$T$1$M$关闭$T$0\',name =\'sidebar_column_ok\',value=\'\',defaultvalue=\'\',valueinfo =\'栏目区块开关\',tips=\'栏目区块大标题调用一级栏目的名称和栏目修饰名称\',bigclass =\'580\'',
  52 => 'pos =\'1\',no_order=\'14\',type=\'4\',style=\'3\',selectd=\'切换卡$T$1$M$链接$T$0\',name =\'index_product_style_type\',value=\'1\',defaultvalue=\'1\',valueinfo =\'展示样式\',tips=\'\',bigclass =\'285\'',
  53 => 'pos =\'3\',no_order=\'14\',type=\'2\',style=\'3\',selectd=\'\',name =\'sidebar_downloadlist_num\',value=\'5\',defaultvalue=\'5\',valueinfo =\'侧栏下载列表数量\',tips=\'\',bigclass =\'352\'',
  54 => 'pos =\'0\',no_order=\'14\',type=\'2\',style=\'3\',selectd=\'\',name =\'email\',value=\'\',defaultvalue=\'\',valueinfo =\'邮箱\',tips=\'关闭会员功能默认显示，开启会员功能则默认关闭\',bigclass =\'309\'',
  55 => 'pos =\'2\',no_order=\'14\',type=\'4\',style=\'3\',selectd=\'开启$T$1$M$关闭$T$0\',name =\'product_bar_column3_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'侧栏3级栏目\',tips=\'\',bigclass =\'580\'',
  56 => 'pos =\'1\',no_order=\'15\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_index_about\',value=\'\',defaultvalue=\'\',valueinfo =\'首页简介区块\',tips=\'\',bigclass =\'0\'',
  57 => 'pos =\'3\',no_order=\'15\',type=\'4\',style=\'3\',selectd=\'$M$全部$T$all$M$推荐$T$com\',name =\'download_bar_list_type\',value=\'all\',defaultvalue=\'all\',valueinfo =\'侧栏列表下载类型\',tips=\'\',bigclass =\'352\'',
  58 => 'pos =\'0\',no_order=\'15\',type=\'2\',style=\'3\',selectd=\'\',name =\'stime\',value=\'\',defaultvalue=\'\',valueinfo =\'营业时间\',tips=\'关闭会员功能默认显示，开启会员功能则默认关闭\',bigclass =\'309\'',
  59 => 'pos =\'2\',no_order=\'15\',type=\'2\',style=\'3\',selectd=\'\',name =\'product_bar_all\',value=\'全部\',defaultvalue=\'全部\',valueinfo =\'全部文字\',tips=\'\',bigclass =\'580\'',
  60 => 'pos =\'1\',no_order=\'16\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_about_title\',value=\'标题\',defaultvalue=\'标题\',valueinfo =\'区块标题\',tips=\'\',bigclass =\'268\'',
  61 => 'pos =\'3\',no_order=\'16\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'download_column3_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'三级栏目开关\',tips=\'\',bigclass =\'352\'',
  62 => 'pos =\'0\',no_order=\'16\',type=\'2\',style=\'3\',selectd=\'\',name =\'otime\',value=\'\',defaultvalue=\'\',valueinfo =\'休业时间\',tips=\'关闭会员功能默认显示，开启会员功能则默认关闭\',bigclass =\'309\'',
  63 => 'pos =\'2\',no_order=\'16\',type=\'4\',style=\'3\',selectd=\'开启$T$1$M$关闭$T$0\',name =\'sidebar_productlist_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'自定义区块开关\',tips=\'\',bigclass =\'580\'',
  64 => 'pos =\'1\',no_order=\'17\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_about_desc\',value=\'描述\',defaultvalue=\'描述\',valueinfo =\'区块描述\',tips=\'\',bigclass =\'268\'',
  65 => 'pos =\'3\',no_order=\'17\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'downloadsidebar_column_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'侧栏栏目开关\',tips=\'\',bigclass =\'352\'',
  66 => 'pos =\'0\',no_order=\'17\',type=\'4\',style=\'3\',selectd=\'开启$T$1$M$关闭$T$0\',name =\'navdropdown_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'导航下拉菜单\',tips=\'\',bigclass =\'309\'',
  67 => 'pos =\'2\',no_order=\'17\',type=\'2\',style=\'3\',selectd=\'\',name =\'sidebar_productlist_title\',value=\'联系我们\',defaultvalue=\'联系我们\',valueinfo =\'自定义区块标题\',tips=\'输入0隐藏\',bigclass =\'580\'',
  68 => 'pos =\'1\',no_order=\'18\',type=\'8\',style=\'3\',selectd=\'\',name =\'home_about_content\',value=\'\',defaultvalue=\'\',valueinfo =\'区块内容\',tips=\'\',bigclass =\'268\'',
  69 => 'pos =\'3\',no_order=\'18\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'sidebar_downloadlist_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'侧栏文章列表开关\',tips=\'\',bigclass =\'352\'',
  70 => 'pos =\'0\',no_order=\'18\',type=\'7\',style=\'3\',selectd=\'\',name =\'bgpic\',value=\'\',defaultvalue=\'\',valueinfo =\'区块背景图\',tips=\'建议上传宽为1920px,高为自定义的背景图\',bigclass =\'309\'',
  71 => 'pos =\'2\',no_order=\'18\',type=\'2\',style=\'3\',selectd=\'\',name =\'csecond\',value=\'CONTACT\',defaultvalue=\'CONTACT\',valueinfo =\'自定义区块副标题\',tips=\'输入0隐藏\',bigclass =\'580\'',
  72 => 'pos =\'1\',no_order=\'19\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_about_long\',value=\'60\',defaultvalue=\'60\',valueinfo =\'内容描述文字最大字符\',tips=\'默认为60个字符\',bigclass =\'268\'',
  73 => 'pos =\'3\',no_order=\'19\',type=\'1\',style=\'3\',selectd=\'\',name =\'img_bar\',value=\'\',defaultvalue=\'\',valueinfo =\'图片模块\',tips=\'\',bigclass =\'0\'',
  74 => 'pos =\'2\',no_order=\'19\',type=\'8\',style=\'3\',selectd=\'\',name =\'side_desc\',value=\'\',defaultvalue=\'\',valueinfo =\'自定义区块内容\',tips=\'\',bigclass =\'580\'',
  75 => 'pos =\'0\',no_order=\'19\',type=\'7\',style=\'3\',selectd=\'\',name =\'nav_ricon\',value=\'\',defaultvalue=\'\',valueinfo =\'左侧图标\',tips=\'\',bigclass =\'309\'',
  76 => 'pos =\'3\',no_order=\'20\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'img_bar_list_open\',value=\'1\',defaultvalue=\'1\',valueinfo =\'侧栏图片列表开关\',tips=\'\',bigclass =\'338\'',
  77 => 'pos =\'0\',no_order=\'20\',type=\'2\',style=\'3\',selectd=\'\',name =\'nav_rtxt\',value=\'\',defaultvalue=\'\',valueinfo =\'左侧文字\',tips=\'字数限制为12\',bigclass =\'309\'',
  78 => 'pos =\'1\',no_order=\'20\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_about_ctitle\',value=\'发展历程\',defaultvalue=\'发展历程\',valueinfo =\'时间轴标题\',tips=\'填0则隐藏\',bigclass =\'268\'',
  79 => 'pos =\'3\',no_order=\'21\',type=\'2\',style=\'3\',selectd=\'\',name =\'img_bar_list_title\',value=\'为您推荐\',defaultvalue=\'为您推荐\',valueinfo =\'侧栏图片列表标题\',tips=\'\',bigclass =\'338\'',
  80 => 'pos =\'0\',no_order=\'21\',type=\'2\',style=\'3\',selectd=\'\',name =\'nav_rtxt1\',value=\'\',defaultvalue=\'\',valueinfo =\'左侧文字手机端\',tips=\'字数限制为8\',bigclass =\'309\'',
  81 => 'pos =\'1\',no_order=\'21\',type=\'4\',style=\'3\',selectd=\'开启$T$1$M$关闭$T$0\',name =\'homet_about_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'时间轴是否开启\',tips=\'\',bigclass =\'268\'',
  82 => 'pos =\'3\',no_order=\'22\',type=\'4\',style=\'3\',selectd=\'$M$全部$T$all$M$推荐$T$com\',name =\'img_bar_list_type\',value=\'all\',defaultvalue=\'all\',valueinfo =\'侧栏列表图片类型\',tips=\'\',bigclass =\'338\'',
  83 => 'pos =\'0\',no_order=\'22\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_position\',value=\'\',defaultvalue=\'\',valueinfo =\'当前位置\',tips=\'\',bigclass =\'0\'',
  84 => 'pos =\'1\',no_order=\'22\',type=\'2\',style=\'3\',selectd=\'\',name =\'homet_about_ctitle\',value=\'\',defaultvalue=\'\',valueinfo =\'内容标题一\',tips=\'不填则不显示\',bigclass =\'268\'',
  85 => 'pos =\'3\',no_order=\'23\',type=\'2\',style=\'3\',selectd=\'\',name =\'img_bar_list_num\',value=\'5\',defaultvalue=\'5\',valueinfo =\'侧栏列表图片数量\',tips=\'\',bigclass =\'338\'',
  86 => 'pos =\'0\',no_order=\'23\',type=\'2\',style=\'3\',selectd=\'\',name =\'position_text\',value=\'你的位置\',defaultvalue=\'你的位置\',valueinfo =\'当前位置标题\',tips=\'\',bigclass =\'345\'',
  87 => 'pos =\'1\',no_order=\'23\',type=\'3\',style=\'3\',selectd=\'\',name =\'homet_about_description\',value=\'\',defaultvalue=\'\',valueinfo =\'内容描述一\',tips=\'不填则不显示\',bigclass =\'268\'',
  88 => 'pos =\'3\',no_order=\'24\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'imgbar_column_open\',value=\'1\',defaultvalue=\'1\',valueinfo =\'侧栏栏目开关\',tips=\'\',bigclass =\'338\'',
  89 => 'pos =\'0\',no_order=\'24\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'tagshow_1\',value=\'1\',defaultvalue=\'1\',valueinfo =\'区域开关\',tips=\'\',bigclass =\'345\'',
  90 => 'pos =\'1\',no_order=\'24\',type=\'2\',style=\'3\',selectd=\'\',name =\'homet_about_ctitle2\',value=\'\',defaultvalue=\'\',valueinfo =\'内容标题二\',tips=\'不填则不显示\',bigclass =\'268\'',
  91 => 'pos =\'3\',no_order=\'25\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'img_column3_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'三级栏目开关\',tips=\'\',bigclass =\'338\'',
  92 => 'pos =\'0\',no_order=\'25\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_foot\',value=\'\',defaultvalue=\'\',valueinfo =\'底部设置\',tips=\'\',bigclass =\'0\'',
  93 => 'pos =\'1\',no_order=\'25\',type=\'3\',style=\'3\',selectd=\'\',name =\'homet_about_description2\',value=\'\',defaultvalue=\'\',valueinfo =\'内容描述二\',tips=\'不填则不显示\',bigclass =\'268\'',
  94 => 'pos =\'3\',no_order=\'26\',type=\'1\',style=\'3\',selectd=\'\',name =\'product_bar\',value=\'\',defaultvalue=\'\',valueinfo =\'产品模块侧边栏\',tips=\'\',bigclass =\'0\'',
  95 => 'pos =\'0\',no_order=\'26\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'link_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'友情链接开关\',tips=\'\',bigclass =\'361\'',
  96 => 'pos =\'1\',no_order=\'26\',type=\'2\',style=\'3\',selectd=\'\',name =\'homet_about_ctitle3\',value=\'\',defaultvalue=\'\',valueinfo =\'内容标题三\',tips=\'不填则不显示\',bigclass =\'268\'',
  97 => 'pos =\'3\',no_order=\'27\',type=\'2\',style=\'3\',selectd=\'\',name =\'product_sidebar_piclist_title\',value=\'热门推荐\',defaultvalue=\'热门推荐\',valueinfo =\'区块标题\',tips=\'\',bigclass =\'327\'',
  98 => 'pos =\'0\',no_order=\'27\',type=\'2\',style=\'3\',selectd=\'\',name =\'footlink_title\',value=\'友情链接\',defaultvalue=\'友情链接\',valueinfo =\'友情链接标题\',tips=\'\',bigclass =\'361\'',
  99 => 'pos =\'1\',no_order=\'27\',type=\'3\',style=\'3\',selectd=\'\',name =\'homet_about_description3\',value=\'\',defaultvalue=\'\',valueinfo =\'内容描述三\',tips=\'不填则不显示\',bigclass =\'268\'',
  100 => 'pos =\'0\',no_order=\'28\',type=\'1\',style=\'3\',selectd=\'\',name =\'global\',value=\'\',defaultvalue=\'\',valueinfo =\'全局参数\',tips=\'\',bigclass =\'0\'',
  101 => 'pos =\'3\',no_order=\'28\',type=\'2\',style=\'3\',selectd=\'\',name =\'product_sidebar_piclist_num\',value=\'5\',defaultvalue=\'5\',valueinfo =\'调用条数\',tips=\'\',bigclass =\'327\'',
  102 => 'pos =\'1\',no_order=\'28\',type=\'2\',style=\'3\',selectd=\'\',name =\'homet_about_ctitle4\',value=\'\',defaultvalue=\'\',valueinfo =\'内容标题四\',tips=\'不填则不显示\',bigclass =\'268\'',
  103 => 'pos =\'0\',no_order=\'29\',type=\'2\',style=\'3\',selectd=\'\',name =\'met_font\',value=\'\',defaultvalue=\'\',valueinfo =\'页面字体\',tips=\'非特殊语种，建议留空使用模板默认字体\',bigclass =\'301\'',
  104 => 'pos =\'3\',no_order=\'29\',type=\'4\',style=\'3\',selectd=\'$M$全部$T$all$M$推荐$T$com\',name =\'product_sidebar_piclist_type\',value=\'all\',defaultvalue=\'all\',valueinfo =\'调用类型\',tips=\'\',bigclass =\'327\'',
  105 => 'pos =\'1\',no_order=\'29\',type=\'3\',style=\'3\',selectd=\'\',name =\'homet_about_description4\',value=\'\',defaultvalue=\'\',valueinfo =\'内容描述四\',tips=\'不填则不显示\',bigclass =\'268\'',
  106 => 'pos =\'0\',no_order=\'30\',type=\'2\',style=\'3\',selectd=\'\',name =\'sub_all\',value=\'全部\',defaultvalue=\'全部\',valueinfo =\'页面文字\',tips=\'\',bigclass =\'301\'',
  107 => 'pos =\'3\',no_order=\'30\',type=\'4\',style=\'3\',selectd=\'当前一级栏目内容列表$T$1$M$TAG标签聚合$T$0\',name =\'product_sidebar_content\',value=\'1\',defaultvalue=\'1\',valueinfo =\'调用内容\',tips=\'默认调用一级栏目内容列表\',bigclass =\'327\'',
  108 => 'pos =\'1\',no_order=\'30\',type=\'2\',style=\'3\',selectd=\'\',name =\'homet_about_ctitle5\',value=\'\',defaultvalue=\'\',valueinfo =\'内容标题五\',tips=\'不填则不显示\',bigclass =\'268\'',
  109 => 'pos =\'0\',no_order=\'31\',type=\'2\',style=\'3\',selectd=\'\',name =\'page_ajax_next\',value=\'加载更多\',defaultvalue=\'加载更多\',valueinfo =\'分页文字\',tips=\'无刷新分页默认文字\',bigclass =\'301\'',
  110 => 'pos =\'1\',no_order=\'31\',type=\'3\',style=\'3\',selectd=\'\',name =\'homet_about_description5\',value=\'\',defaultvalue=\'\',valueinfo =\'内容描述五\',tips=\'不填则不显示\',bigclass =\'268\'',
  111 => 'pos =\'0\',no_order=\'32\',type=\'2\',style=\'3\',selectd=\'\',name =\'nodata\',value=\'没有数据了\',defaultvalue=\'没有数据了\',valueinfo =\'无数据提示\',tips=\'\',bigclass =\'301\'',
  112 => 'pos =\'1\',no_order=\'32\',type=\'2\',style=\'3\',selectd=\'\',name =\'homet_about_ctitle6\',value=\'\',defaultvalue=\'\',valueinfo =\'内容标题六\',tips=\'不填则不显示\',bigclass =\'268\'',
  113 => 'pos =\'0\',no_order=\'33\',type=\'2\',style=\'3\',selectd=\'\',name =\'search_placeholder\',value=\'请输入内容关键词\',defaultvalue=\'请输入内容关键词\',valueinfo =\'搜索文字\',tips=\'\',bigclass =\'301\'',
  114 => 'pos =\'1\',no_order=\'33\',type=\'3\',style=\'3\',selectd=\'\',name =\'homet_about_description6\',value=\'\',defaultvalue=\'\',valueinfo =\'内容描述六\',tips=\'不填则不显示\',bigclass =\'268\'',
  115 => 'pos =\'0\',no_order=\'34\',type=\'9\',style=\'3\',selectd=\'\',name =\'first_color\',value=\'#000000\',defaultvalue=\'#000000\',valueinfo =\'模板主色调\',tips=\'\',bigclass =\'301\'',
  116 => 'pos =\'1\',no_order=\'34\',type=\'2\',style=\'3\',selectd=\'\',name =\'homet_about_ctitle7\',value=\'\',defaultvalue=\'\',valueinfo =\'内容标题七\',tips=\'不填则不显示\',bigclass =\'268\'',
  117 => 'pos =\'0\',no_order=\'35\',type=\'4\',style=\'3\',selectd=\'当前窗口打开$T$_self$M$新窗口打开$T$_blank$M$\',name =\'met_listurlblank\',value=\'_self\',defaultvalue=\'_self\',valueinfo =\'页面链接\',tips=\'\',bigclass =\'301\'',
  118 => 'pos =\'1\',no_order=\'35\',type=\'3\',style=\'3\',selectd=\'\',name =\'homet_about_description7\',value=\'\',defaultvalue=\'\',valueinfo =\'内容描述七\',tips=\'不填则不显示\',bigclass =\'268\'',
  119 => 'pos =\'0\',no_order=\'36\',type=\'1\',style=\'3\',selectd=\'\',name =\'banner\',value=\'\',defaultvalue=\'\',valueinfo =\'banner设置\',tips=\'\',bigclass =\'0\'',
  120 => 'pos =\'1\',no_order=\'36\',type=\'2\',style=\'3\',selectd=\'\',name =\'homet_about_ctitle8\',value=\'\',defaultvalue=\'\',valueinfo =\'内容标题八\',tips=\'不填则不显示\',bigclass =\'268\'',
  121 => 'pos =\'0\',no_order=\'37\',type=\'4\',style=\'3\',selectd=\'$M$提示$T$1\',name =\'info\',value=\'1\',defaultvalue=\'1\',valueinfo =\'提示\',tips=\'此banner是图片不适合设置高度，如果觉得banner尺寸不合适请更换banner尺寸\',bigclass =\'332\'',
  122 => 'pos =\'1\',no_order=\'37\',type=\'3\',style=\'3\',selectd=\'\',name =\'homet_about_description8\',value=\'\',defaultvalue=\'\',valueinfo =\'内容描述八\',tips=\'不填则不显示\',bigclass =\'268\'',
  123 => 'pos =\'0\',no_order=\'38\',type=\'9\',style=\'3\',selectd=\'\',name =\'page_top_bgcolor\',value=\'#ccc\',defaultvalue=\'#ccc\',valueinfo =\'内页无banner背景色\',tips=\'\',bigclass =\'332\'',
  124 => 'pos =\'1\',no_order=\'38\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_index_landingpage\',value=\'\',defaultvalue=\'\',valueinfo =\'首页落地页\',tips=\'\',bigclass =\'0\'',
  125 => 'pos =\'0\',no_order=\'39\',type=\'9\',style=\'3\',selectd=\'\',name =\'bannersub_color\',value=\'#fff\',defaultvalue=\'#fff\',valueinfo =\'内页无banner字体色\',tips=\'\',bigclass =\'332\'',
  126 => 'pos =\'1\',no_order=\'39\',type=\'4\',style=\'3\',selectd=\'开启$T$1$M$关闭$T$0\',name =\'tagshow_1\',value=\'1\',defaultvalue=\'1\',valueinfo =\'区块开关\',tips=\'\',bigclass =\'366\'',
  127 => 'pos =\'0\',no_order=\'40\',type=\'2\',style=\'3\',selectd=\'\',name =\'btn_margin\',value=\'5\',defaultvalue=\'5\',valueinfo =\'电脑端按钮之间的边距\',tips=\'默认为5px\',bigclass =\'332\'',
  128 => 'pos =\'1\',no_order=\'40\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_landingpage_title\',value=\'标题\',defaultvalue=\'标题\',valueinfo =\'区块标题\',tips=\'\',bigclass =\'366\'',
  129 => 'pos =\'0\',no_order=\'41\',type=\'2\',style=\'3\',selectd=\'\',name =\'mbtn_margin\',value=\'5\',defaultvalue=\'5\',valueinfo =\'手机端按钮之间的边距\',tips=\'默认为5px\',bigclass =\'332\'',
  130 => 'pos =\'1\',no_order=\'41\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_landingpage_desc\',value=\'描述\',defaultvalue=\'描述\',valueinfo =\'区块描述\',tips=\'\',bigclass =\'366\'',
  131 => 'pos =\'0\',no_order=\'42\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_contact\',value=\'\',defaultvalue=\'\',valueinfo =\'底部联系信息设置\',tips=\'\',bigclass =\'0\'',
  132 => 'pos =\'1\',no_order=\'42\',type=\'8\',style=\'3\',selectd=\'\',name =\'home_landingpage_content\',value=\'\',defaultvalue=\'\',valueinfo =\'区块内容\',tips=\'\',bigclass =\'366\'',
  133 => 'pos =\'0\',no_order=\'43\',type=\'2\',style=\'3\',selectd=\'\',name =\'footinfo_tel\',value=\'\',defaultvalue=\'\',valueinfo =\'服务热线\',tips=\'\',bigclass =\'241\'',
  134 => 'pos =\'1\',no_order=\'43\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_index_news\',value=\'\',defaultvalue=\'\',valueinfo =\'首页新闻区块\',tips=\'\',bigclass =\'0\'',
  135 => 'pos =\'0\',no_order=\'44\',type=\'2\',style=\'3\',selectd=\'\',name =\'footinfo_dsc\',value=\'\',defaultvalue=\'\',valueinfo =\'描述文字\',tips=\'\',bigclass =\'241\'',
  136 => 'pos =\'1\',no_order=\'44\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_news_title\',value=\'标题\',defaultvalue=\'标题\',valueinfo =\'区块标题\',tips=\'\',bigclass =\'316\'',
  137 => 'pos =\'0\',no_order=\'45\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'weixin\',value=\'1\',defaultvalue=\'1\',valueinfo =\'微信\',tips=\'\',bigclass =\'241\'',
  138 => 'pos =\'1\',no_order=\'45\',type=\'3\',style=\'3\',selectd=\'\',name =\'index_news_desc\',value=\'描述\',defaultvalue=\'描述\',valueinfo =\'区块描述\',tips=\'\',bigclass =\'316\'',
  139 => 'pos =\'0\',no_order=\'46\',type=\'7\',style=\'3\',selectd=\'\',name =\'weixin_img\',value=\'\',defaultvalue=\'\',valueinfo =\'微信二维码\',tips=\'\',bigclass =\'241\'',
  140 => 'pos =\'1\',no_order=\'46\',type=\'6\',style=\'3\',selectd=\'\',name =\'home_news_id\',value=\'\',defaultvalue=\'\',valueinfo =\'右侧调用栏目\',tips=\'调用指定栏目内容下列表\',bigclass =\'316\'',
  141 => 'pos =\'1\',no_order=\'47\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_news_num\',value=\'3\',defaultvalue=\'3\',valueinfo =\'右侧调用条数\',tips=\'默认调用3条\',bigclass =\'316\'',
  142 => 'pos =\'0\',no_order=\'47\',type=\'2\',style=\'3\',selectd=\'\',name =\'weixintext\',value=\'关注公众号\',defaultvalue=\'关注公众号\',valueinfo =\'微信标题\',tips=\'\',bigclass =\'241\'',
  143 => 'pos =\'0\',no_order=\'48\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'footinfo_qq_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'QQ\',tips=\'\',bigclass =\'241\'',
  144 => 'pos =\'1\',no_order=\'48\',type=\'4\',style=\'3\',selectd=\'$M$全部$T$all$M$推荐$T$com\',name =\'home_news_type\',value=\'all\',defaultvalue=\'all\',valueinfo =\'右侧调用类型\',tips=\'\',bigclass =\'316\'',
  145 => 'pos =\'0\',no_order=\'49\',type=\'4\',style=\'3\',selectd=\'$M$个人QQ$T$1$M$企业营销QQ$T$2\',name =\'foot_info_qqtype\',value=\'1\',defaultvalue=\'1\',valueinfo =\'QQ类型\',tips=\'个人QQ和企业营销QQ超链接结构不一样，因此请务必选择正确。\',bigclass =\'241\'',
  146 => 'pos =\'1\',no_order=\'49\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_news_img_maxnum\',value=\'80\',defaultvalue=\'80\',valueinfo =\'右侧描述文字字数限制\',tips=\'默认为80个字符\',bigclass =\'316\'',
  147 => 'pos =\'0\',no_order=\'50\',type=\'2\',style=\'3\',selectd=\'\',name =\'footinfo_qq\',value=\'\',defaultvalue=\'\',valueinfo =\'QQ号码\',tips=\'点击QQ链接可直接对话，需要先到 shang.qq.com 免费开通。<br/>企业营销QQ 无需开通\',bigclass =\'241\'',
  148 => 'pos =\'1\',no_order=\'50\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_product_right_w\',value=\'248\',defaultvalue=\'248\',valueinfo =\'左侧缩略图宽\',tips=\'默认248px\',bigclass =\'316\'',
  149 => 'pos =\'0\',no_order=\'51\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'footinfo_sina_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'新浪微博\',tips=\'\',bigclass =\'241\'',
  150 => 'pos =\'1\',no_order=\'51\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_product_right_h\',value=\'155\',defaultvalue=\'155\',valueinfo =\'左侧缩略图高\',tips=\'默认155px\',bigclass =\'316\'',
  151 => 'pos =\'0\',no_order=\'52\',type=\'2\',style=\'3\',selectd=\'\',name =\'footinfo_sina\',value=\'\',defaultvalue=\'\',valueinfo =\'新浪微博网址\',tips=\'请输入微博网址\',bigclass =\'241\'',
  152 => 'pos =\'1\',no_order=\'52\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_news_right_num\',value=\'2\',defaultvalue=\'2\',valueinfo =\'左侧调用条数\',tips=\'默认调用2条\',bigclass =\'316\'',
  153 => 'pos =\'0\',no_order=\'53\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'footinfo_twitterok\',value=\'0\',defaultvalue=\'0\',valueinfo =\'twitter（推特）\',tips=\'\',bigclass =\'241\'',
  154 => 'pos =\'1\',no_order=\'53\',type=\'6\',style=\'3\',selectd=\'\',name =\'home_news_right_id\',value=\'\',defaultvalue=\'\',valueinfo =\'左侧调用栏目\',tips=\'调用指定栏目内容下列表\',bigclass =\'316\'',
  155 => 'pos =\'0\',no_order=\'54\',type=\'2\',style=\'3\',selectd=\'\',name =\'footinfo_twitter\',value=\'\',defaultvalue=\'\',valueinfo =\'twitter网址\',tips=\'\',bigclass =\'241\'',
  156 => 'pos =\'1\',no_order=\'54\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_news_desc_num\',value=\'80\',defaultvalue=\'80\',valueinfo =\'左侧描述文字字数限制\',tips=\'默认为80个字符\',bigclass =\'316\'',
  157 => 'pos =\'0\',no_order=\'55\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'footinfo_googleok\',value=\'0\',defaultvalue=\'0\',valueinfo =\'google+\',tips=\'\',bigclass =\'241\'',
  158 => 'pos =\'1\',no_order=\'55\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_index_case\',value=\'\',defaultvalue=\'\',valueinfo =\'首页合作伙伴\',tips=\'\',bigclass =\'0\'',
  159 => 'pos =\'0\',no_order=\'56\',type=\'2\',style=\'3\',selectd=\'\',name =\'footinfo_google\',value=\'\',defaultvalue=\'\',valueinfo =\'google+网址\',tips=\'\',bigclass =\'241\'',
  160 => 'pos =\'1\',no_order=\'56\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_case_title\',value=\'标题\',defaultvalue=\'标题\',valueinfo =\'区块标题\',tips=\'\',bigclass =\'276\'',
  161 => 'pos =\'0\',no_order=\'57\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'footinfo_facebookok\',value=\'0\',defaultvalue=\'0\',valueinfo =\'Facebook\',tips=\'\',bigclass =\'241\'',
  162 => 'pos =\'1\',no_order=\'57\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_case_desc\',value=\'描述\',defaultvalue=\'描述\',valueinfo =\'区块描述\',tips=\'\',bigclass =\'276\'',
  163 => 'pos =\'0\',no_order=\'58\',type=\'2\',style=\'3\',selectd=\'\',name =\'footinfo_facebook\',value=\'\',defaultvalue=\'\',valueinfo =\'Facebook网址\',tips=\'\',bigclass =\'241\'',
  164 => 'pos =\'1\',no_order=\'58\',type=\'6\',style=\'3\',selectd=\'\',name =\'home_case_id\',value=\'\',defaultvalue=\'\',valueinfo =\'栏目选择\',tips=\'\',bigclass =\'276\'',
  165 => 'pos =\'0\',no_order=\'59\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'footinfo_emailok\',value=\'0\',defaultvalue=\'0\',valueinfo =\'邮箱\',tips=\'\',bigclass =\'241\'',
  166 => 'pos =\'1\',no_order=\'59\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_case_num\',value=\'8\',defaultvalue=\'8\',valueinfo =\'调用条数\',tips=\'默认调用8条\',bigclass =\'276\'',
  167 => 'pos =\'0\',no_order=\'60\',type=\'2\',style=\'3\',selectd=\'\',name =\'footinfo_email\',value=\'\',defaultvalue=\'\',valueinfo =\'邮箱地址\',tips=\'\',bigclass =\'241\'',
  168 => 'pos =\'1\',no_order=\'60\',type=\'4\',style=\'3\',selectd=\'全部$T$all$M$推荐$T$com\',name =\'home_case_type\',value=\'all\',defaultvalue=\'all\',valueinfo =\'调用类型\',tips=\'\',bigclass =\'276\'',
  169 => 'pos =\'1\',no_order=\'61\',type=\'4\',style=\'3\',selectd=\'纯展示$T$0$M$超链接$T$1\',name =\'home_case_linkok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'展示方式\',tips=\'默认为超链接\',bigclass =\'276\'',
  170 => 'pos =\'1\',no_order=\'62\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_case_column_xxl\',value=\'4\',defaultvalue=\'4\',valueinfo =\'大尺寸电脑显示列数\',tips=\'浏览器宽度大于1600像素时\',bigclass =\'276\'',
  171 => 'pos =\'1\',no_order=\'63\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_case_column_lg\',value=\'4\',defaultvalue=\'4\',valueinfo =\'普通电脑显示列数\',tips=\'浏览器宽度大于992像素小于1600像素时\',bigclass =\'276\'',
  172 => 'pos =\'1\',no_order=\'64\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_case_column_md\',value=\'2\',defaultvalue=\'2\',valueinfo =\'平板显示列数\',tips=\'浏览器宽度大于768像素小于992像素时\',bigclass =\'276\'',
  173 => 'pos =\'1\',no_order=\'65\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_case_column_xs\',value=\'1\',defaultvalue=\'1\',valueinfo =\'手机显示列数\',tips=\'浏览器宽度小于768像素时\',bigclass =\'276\'',
  174 => 'pos =\'1\',no_order=\'66\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_case_imgw\',value=\'400\',defaultvalue=\'400\',valueinfo =\'缩略图宽\',tips=\'默认为400px\',bigclass =\'276\'',
  175 => 'pos =\'1\',no_order=\'67\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_case_imgh\',value=\'250\',defaultvalue=\'250\',valueinfo =\'缩略图高\',tips=\'默认为250px\',bigclass =\'276\'',
);
$no='metv7s';
$devices='0';
		$re['sql'] = $sql;
		$re['no'] = $no;
		$re['devices'] = $devices;
		return $re;
	}
}

# This program is an open source system, commercial use, please consciously to purchase commercial license.
# Copyright (C) MetInfo Co., Ltd. (http://www.metinfo.cn). All rights reserved.
?>